/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maidbooking;

import javax.swing.JOptionPane;

/**
 *
 * @author fisot
 */
public class Maid_Update_Form extends javax.swing.JFrame {
    private String userEmail = "";
    /**
     * Creates new form Maid_Update_Form
     */
    public Maid_Update_Form() {
        UserSession session = UserSession.getInstance();
        this.userEmail = session.getUserEmail();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t4am_6am = new javax.swing.JRadioButton();
        t6am_8am = new javax.swing.JRadioButton();
        t8am_10am = new javax.swing.JRadioButton();
        t2pm_4pm = new javax.swing.JRadioButton();
        t4pm_6pm = new javax.swing.JRadioButton();
        t12pm_2pm = new javax.swing.JRadioButton();
        t8pm_10pm = new javax.swing.JRadioButton();
        t10pm_12am = new javax.swing.JRadioButton();
        t6pm_8pm = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        t10am_12pm = new javax.swing.JRadioButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Update Details");

        jLabel2.setText("Charges");

        jButton1.setText("Update Budget");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        t4am_6am.setText("t4am_6am");
        t4am_6am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4am_6amActionPerformed(evt);
            }
        });

        t6am_8am.setText("t6am_8am");
        t6am_8am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6am_8amActionPerformed(evt);
            }
        });

        t8am_10am.setText("t8am_10am");

        t2pm_4pm.setText("12pm-4pm");

        t4pm_6pm.setText("4pm-6pm");
        t4pm_6pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4pm_6pmActionPerformed(evt);
            }
        });

        t12pm_2pm.setText("t12pm_2pm");
        t12pm_2pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t12pm_2pmActionPerformed(evt);
            }
        });

        t8pm_10pm.setText("t8pm_10pm");
        t8pm_10pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8pm_10pmActionPerformed(evt);
            }
        });

        t10pm_12am.setText("t10pm_12am");
        t10pm_12am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10pm_12amActionPerformed(evt);
            }
        });

        t6pm_8pm.setText("t6pm_8pm");
        t6pm_8pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6pm_8pmActionPerformed(evt);
            }
        });

        jButton2.setText("Update availability");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        t10am_12pm.setText("t10am_12pm");
        t10am_12pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10am_12pmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(t4am_6am)
                                        .addComponent(t6am_8am)
                                        .addComponent(t8am_10am)
                                        .addComponent(t12pm_2pm)
                                        .addComponent(t2pm_4pm)
                                        .addComponent(t4pm_6pm)
                                        .addComponent(t10am_12pm))
                                    .addGap(64, 64, 64)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(t10pm_12am)
                                        .addComponent(t8pm_10pm)
                                        .addComponent(t6pm_8pm))
                                    .addGap(11, 11, 11)))
                            .addComponent(jButton3))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t4am_6am)
                            .addComponent(t6pm_8pm))
                        .addGap(18, 18, 18)
                        .addComponent(t6am_8am)
                        .addGap(18, 18, 18)
                        .addComponent(t8am_10am)
                        .addGap(18, 18, 18)
                        .addComponent(t12pm_2pm)
                        .addGap(18, 18, 18)
                        .addComponent(t2pm_4pm)
                        .addGap(18, 18, 18)
                        .addComponent(t4pm_6pm)
                        .addGap(18, 18, 18)
                        .addComponent(t10am_12pm)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t8pm_10pm)
                        .addGap(18, 18, 18)
                        .addComponent(t10pm_12am)
                        .addGap(230, 230, 230)))
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t12pm_2pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t12pm_2pmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t12pm_2pmActionPerformed

    private void t10pm_12amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10pm_12amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t10pm_12amActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Maid_Homepage maidhomepage = new Maid_Homepage();
        maidhomepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int charges =  Integer.parseInt(jTextField1.getText());
       
        
        
        
      Maid_APIs updatebudge = new Maid_APIs();
      boolean response = updatebudge.ChangeMaidCharges(charges, this.userEmail);
      if(response){
          JOptionPane.showMessageDialog(null, "Charges Updated");
      }else{
          JOptionPane.showMessageDialog(null, "Changes cannot be made");

      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t4am_6amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4am_6amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4am_6amActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Maid_APIs changeTiming = new Maid_APIs(); 
        boolean response = changeTiming.ChangeAvaliabilityTiming(
                this.userEmail,
                t4am_6am.isSelected(), 
                t6am_8am.isSelected(),
                t8am_10am.isSelected(), 
                t10am_12pm.isSelected(),
                t12pm_2pm.isSelected(),
                t2pm_4pm.isSelected(), 
                t4pm_6pm.isSelected(), 
                t6pm_8pm.isSelected(), 
                t8pm_10pm.isSelected(), 
                t10pm_12am.isSelected()
        );
        
        if(response){
          JOptionPane.showMessageDialog(null, "Avaliability Updated");
      }else{
          JOptionPane.showMessageDialog(null, "Changes cannot be made");

      }
        
        
        
    
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t6am_8amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6am_8amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6am_8amActionPerformed

    private void t4pm_6pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4pm_6pmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4pm_6pmActionPerformed

    private void t8pm_10pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8pm_10pmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8pm_10pmActionPerformed

    private void t6pm_8pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6pm_8pmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6pm_8pmActionPerformed

    private void t10am_12pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10am_12pmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t10am_12pmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maid_Update_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maid_Update_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maid_Update_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maid_Update_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maid_Update_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton t10am_12pm;
    private javax.swing.JRadioButton t10pm_12am;
    private javax.swing.JRadioButton t12pm_2pm;
    private javax.swing.JRadioButton t2pm_4pm;
    private javax.swing.JRadioButton t4am_6am;
    private javax.swing.JRadioButton t4pm_6pm;
    private javax.swing.JRadioButton t6am_8am;
    private javax.swing.JRadioButton t6pm_8pm;
    private javax.swing.JRadioButton t8am_10am;
    private javax.swing.JRadioButton t8pm_10pm;
    // End of variables declaration//GEN-END:variables
}
